# Generated by Django 4.1.5 on 2023-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerMeter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
